#!/usr/bin/env bash

COVERAGE_FLAGS="--cov=django_north --cov-report xml --cov-report term --cov-report html --cov-config .coveragerc"

if [ $# > 0 ]; then
    TESTS=$*
else
    TESTS="tests/"
fi

if [ -z ${COVERAGE+x} ];
    then
    COVERAGE_FLAGS=""
fi

pytest -vv $COVERAGE_FLAGS $TESTS
